### ISSUE TITLE
[PE-D][Tester C] Unexpected invalid VRN, maybe documentation bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-3/tp#213]
![image.png](https://raw.githubusercontent.com/blackpanther9229/ped/main/files/e621e5d5-0bf8-447f-95b3-a051553caf9a.png)

![image.png](https://raw.githubusercontent.com/blackpanther9229/ped/main/files/cbb8a9fd-8337-459b-8eb6-9802b442f257.png)

As you guys can see, my VRN correctly follows the format given in both the glossary and message error. However, 
it seems to be invalid. Maybe I didn't read the documentation clearly?

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: blackpanther9229/ped#3

**Comment by xhamyo** [comment]
Invalid VRN used.
