### ISSUE TITLE
[PE-D][Tester A] Inaccurate description for VRN in the user guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-3/tp#217]
![image.png](https://raw.githubusercontent.com/Nicholas-Cheng-De-Fei/ped/main/files/949ad43f-16e7-4557-aadc-52ce682e5357.png)

Firstly in the user guide it is specified that the vehicle registration plate the first 3 letters must contain some letters but in actuality the first letter if we based on the target audience which is a person who works at a car repair shop, then it should state the first letter should be S since all Singapore private vehicles start with S and from testing only car plat numbers with S are accepted, the rest will be rejected

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Nicholas-Cheng-De-Fei/ped#1

**Comment by limyuquan** [comment]
good suggestion
