### ISSUE TITLE
[PE-D][Tester B] Edit Feature fails to reinforce VRN format

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-3/tp#221]
Refer to Screenshot attached:
Trying to edit a client's VRN number gives invalid format error even though the number follows exact format given in user guide and also error message.
Expected: Vehicle Registration Number should be edited and replaced by new.
Actual: invalid format error

![Screenshot 2024-11-08 at 4.39.13 PM.png](https://raw.githubusercontent.com/Nihirraa/ped/main/files/030b7ed4-67d1-4bc6-8f04-907b0e4f6ff7.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Nihirraa/ped#2

**Comment by limyuquan** [comment]
vrn not according to LTA
