### ISSUE TITLE
[PE-D][Tester B] Edit Command shows incorrect error messages for index numbers longer than Long (>MAX)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-3/tp#225]
In the first case the index provided is 20 and the error message shown is correct.
![Screenshot 2024-11-08 at 4.52.06 PM.png](https://raw.githubusercontent.com/Nihirraa/ped/main/files/8ab3ef56-2b73-4148-9c92-10586024bc12.png)
In the second case, the index provided is a long number and an overflow error occurs and the error message shown is incorrect
![Screenshot 2024-11-08 at 4.51.54 PM.png](https://raw.githubusercontent.com/Nihirraa/ped/main/files/0c27e02e-95f9-4237-8b2d-00871850eb1d.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Nihirraa/ped#3

**Comment by calebyyy** [comment]
<img width="644" alt="Screenshot 2024-11-09 at 2 55 27 PM" src="https://github.com/user-attachments/assets/52b3cb41-0298-4206-b2f1-af7a0f1786f1">

Per guidelines, integer overflow is not considered a bug
