### ISSUE TITLE
[PE-D][Tester A] Vehicle registration number accepts non cars

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-3/tp#227]
![image.png](https://raw.githubusercontent.com/Nicholas-Cheng-De-Fei/ped/main/files/c1935721-40c8-47ad-b5b8-a40861d3c810.png)

Based on the user guide the developer guide the target audience is for people who works in a car workshop. Thus I will have the assumption that the application is for people who only services cars.

Thus from the image above the letters PC are usually reserved for private buses as mentioned by the link provided in the user guide. Therefore I believe this should not be the case as the vehicle is not a car but a bus.

Therefore it should reject inputs such as this.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Nicholas-Cheng-De-Fei/ped#3

**Comment by limyuquan** [comment]
more of a feature bug
