### ISSUE TITLE
[PE-D][Tester E] Test case involving Find command can fail in specific scenarios

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-3/tp#229]
![Screenshot 2024-11-08 at 5.04.49 PM.png](https://raw.githubusercontent.com/miloaisdino/ped/main/files/2bac50aa-5380-4402-940f-0f3ff3ba9406.png)

In test case 2.3, I notice in the very rare case someone's name is the same as the car VRN that is being searched, the client will be listed.

A more accurate test case will be:
Test case: find SJH9514L
(SJH9514L car or **name** doesn't exist) Expected: No clients are Listed. List will not be populated

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: miloaisdino/ped#4

**Comment by limyuquan** [comment]
updated
