### ISSUE TITLE
[PE-D][Tester B] add-car Feature doesn't allow adding car to client and shows error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-3/tp#230]
Add Car feature shows invalid Vehicle Registration Number format error even though all VRN number specifications have been followed and a valid VRN number has been provided. 
This bug makes it impossible to add car to any client as it always shows the same error.
Expected: Car should be added to the client
Actual: Error message is shown

![Screenshot 2024-11-08 at 5.07.14 PM.png](https://raw.githubusercontent.com/Nihirraa/ped/main/files/49e9ba85-ecef-4c97-8f1c-e3bcfb6562ea.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Nihirraa/ped#4

**Comment by limyuquan** [comment]
invalid checksum used in testing
