### ISSUE TITLE
[PE-D][Tester E] Concurrent edits cause info not to be updated

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-3/tp#241]
When I open 2 windows of MATER, if i add car on one of them, it doesnt appear in the other, which is unexpected behaviour.

Command to reproduce: `add-client n/NEW p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25`

![Screenshot 2024-11-08 at 5.44.12 PM.png](https://raw.githubusercontent.com/miloaisdino/ped/main/files/e65576a2-1359-4f2d-98e6-808cd823111c.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: miloaisdino/ped#8

**Comment by limyuquan** [comment]
cant fix
