### ISSUE TITLE
[PE-D][Tester E] Error in acceptable VRN format in error descriptor

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-3/tp#242]
![Screenshot 2024-11-08 at 5.48.59 PM.png](https://raw.githubusercontent.com/miloaisdino/ped/main/files/be584a7d-85cb-45ed-af51-5832225f07d0.png)
Error descriptor

![Screenshot 2024-11-08 at 5.49.57 PM.png](https://raw.githubusercontent.com/miloaisdino/ped/main/files/bbc06d3a-547f-485c-9be3-5ed8e145a7c9.png)
DG

I noticed there was an inconsistency between the error descriptor and the possible valid VRNs stated in the DG used for testing. It seems that the VRNs in the DG are correct. Hence it will be good to update the error descriptor (eg XXX refers to one or more capitalised characters)

Command to reproduce error: 
`add-car 1 vrn/ABC9999 vin/1G6ABC129P5123456 make/Toyota model/Corolla`

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: miloaisdino/ped#9

**Comment by limyuquan** [comment]
cannot fix
