### ISSUE TITLE
[PE-D][Tester B] Issue feature is not case insensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-3/tp#252]
Issue feature allows to add two exactly same issues due to its case sensitivity. You can consider making it case sensitive to improve this bug

![Screenshot 2024-11-08 at 6.20.30 PM.png](https://raw.githubusercontent.com/Nihirraa/ped/main/files/0b1399ec-7147-4343-90cf-8aef8d222977.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Nihirraa/ped#6

**Comment by limyuquan** [comment]
cant fix in feature freeze
